"""The inner loop: plan, author, execute, read the failure, revise, then hand to the host.

Today the agent authors a model once. `symplex/connectors/compute.py` sets
`max_tool_calls: 4` and there is no loop that reads a test failure and revises, so the
first program that runs at all is the program that ships. This module is the missing
iterate-until-it-actually-works loop, and it ends where the agent's authority ends.

Three properties matter more than the control flow:

**Every attempt is persisted, including the losers.** A failed attempt carries its
classification and the exact guidance that was issued in response. The repository's rule
is that losing branches stay inspectable; an inner loop that quietly discards its first
two attempts would hide precisely the evidence a reviewer needs to judge whether the
third one is any good.

**Nothing is fabricated when the budget runs out.** A loop that exhausts its attempts
returns what it actually has, labelled `attempts_exhausted`, with `overall_success` false.
Partial results with an honest status are useful; a manufactured success is worse than
no result at all.

**The last step is host verification the agent cannot influence.** The agent's own
diagnostics and the host's recomputation are recorded separately and labelled separately
-- `maker_reported` and `host_recomputed` -- and they are never merged into a single
verdict. When the agent's tests all pass and the host's independent recomputation of the
same generated bytes fails, that disagreement is the finding. It means the tests did not
constrain what they claimed to constrain, which is exactly the maker-reported-boolean
risk named in `docs/release-audit.md` finding 2. The loop stops and returns to the plan
rather than buying another code attempt, because more code will not fix a test suite that
cannot see the defect.

The provider and the sandbox never appear here. The caller injects `execute`, so the
whole loop runs offline against a fake with no network, no provider and no cost.
"""

from symplex.authoring.failures import (
    ExecutionFailure,
    escalate,
    is_retryable,
    parse_execution_failure,
    revision_guidance,
)
from symplex.authoring.plan import parse_plan, validate_plan
from symplex.authoring.testspec import protected_subset, summarize_outcomes
from symplex.connectors.compute import (
    MAX_INPUT_BYTES,
    MAX_REVISION_BYTES,
    MAX_REVISION_FILES,
)
from symplex.core.contracts import Invalid, digest
from symplex.infrastructure.storage import BudgetExhausted

VERSION = "authoring-inner-loop-v1"
DEFAULT_ATTEMPTS = 3
MAX_ATTEMPTS = 5
MAX_STREAM_RECORD = 4000
MAX_RECORDED_FILES = 24
MAX_OUTPUT_FILES = 12
MAX_OUTPUT_BYTES = 5_000_000

ATTEMPT_KIND = "authoring_attempt"
DISCREPANCY_KIND = "authoring_discrepancy"

TERMINATION_STATUSES = (
    "converged",
    "attempts_exhausted",
    "escalated_to_plan",
    "budget_exhausted",
    "cancelled",
)

MAKER = "maker_reported"
HOST = "host_recomputed"

SCOPE = (
    "An agent-authored model iterated until its own code runs and its own tests pass, "
    "then checked by host recomputation of the generated bytes. Convergence establishes "
    "that the program does what its author intended and that the host's frozen numerical "
    "checks hold on the produced outputs. It does not establish that the model is "
    "correct, well-posed, identifiable or empirically valid, and no result here is "
    "independent scientific evidence."
)

DISCREPANCY_HEADLINE = (
    "MAKER/HOST DISCREPANCY: the agent's own tests all reported pass while the host's "
    "independent recomputation of the same generated outputs failed. The agent's "
    "diagnostics did not detect the defect they were written to catch, so the passing "
    "booleans carry no information. Treat the maker-reported result as unsupported and "
    "return to the plan; another code attempt cannot fix a test suite that cannot see the "
    "problem. This is the failure mode recorded in docs/release-audit.md finding 2."
)


def _envelope(attempt_budget):
    return {
        "max_attempts": attempt_budget,
        "max_output_files": MAX_OUTPUT_FILES,
        "max_output_bytes_per_file": MAX_OUTPUT_BYTES,
        "max_total_output_bytes": MAX_REVISION_BYTES,
        "max_input_bytes": MAX_INPUT_BYTES,
        "max_revision_files": MAX_REVISION_FILES,
        "max_recorded_stream_chars": MAX_STREAM_RECORD,
    }


def _text(value, limit=MAX_STREAM_RECORD):
    if value is None:
        return ""
    if not isinstance(value, str):
        raise Invalid("Sandbox streams must be text")
    return value[-limit:]


def _files(value):
    if value is None:
        return []
    if not isinstance(value, list) or len(value) > 256:
        raise Invalid("Executor must return generated files as a bounded list")
    files = []
    for item in value:
        if isinstance(item, str):
            item = {"filename": item}
        if not isinstance(item, dict):
            raise Invalid("Generated file entries must be names or mappings")
        name = item.get("filename") or item.get("path") or item.get("name")
        if not isinstance(name, str) or not name.strip():
            raise Invalid("Generated files must carry a filename")
        size = item.get("bytes")
        if size is not None and (
            isinstance(size, bool) or not isinstance(size, int) or size < 0
        ):
            raise Invalid("Generated file sizes must be nonnegative integers")
        files.append(
            {
                "filename": name.rsplit("/", 1)[-1][:200],
                "id": item.get("id") if isinstance(item.get("id"), str) else None,
                "sha256": item.get("sha256")
                if isinstance(item.get("sha256"), str)
                else None,
                "bytes": size,
            }
        )
    return files


def _identifier(value, label):
    if value is None:
        return None
    if not isinstance(value, str) or not value.strip() or len(value) > 200:
        raise Invalid("Executor returned an invalid " + label)
    return value


def _normalize_result(result):
    if not isinstance(result, dict):
        raise Invalid("The injected executor must return a mapping")
    file_ids = result.get("file_ids")
    if file_ids is not None:
        if not isinstance(file_ids, list) or len(file_ids) > 128:
            raise Invalid("Executor returned an invalid generated file ID list")
        file_ids = [_identifier(i, "file ID") for i in file_ids]
    return {
        "stdout": _text(result.get("stdout"), MAX_STREAM_RECORD * 4),
        "stderr": _text(result.get("stderr"), MAX_STREAM_RECORD * 4),
        "files": _files(result.get("files")),
        "agent_tests": result.get("agent_tests") or [],
        "package_id": _identifier(result.get("package_id"), "compute package ID"),
        "run_id": _identifier(result.get("run_id"), "compute run ID"),
        "file_ids": file_ids or [],
        "summary": _text(result.get("summary"), MAX_STREAM_RECORD),
    }


def _envelope_breach(result, envelope):
    files = result["files"]
    if len(files) > envelope["max_output_files"]:
        return (
            f"The attempt produced {len(files)} output files; the collection envelope is "
            f"{envelope['max_output_files']}."
        )
    total = 0
    for item in files:
        size = item["bytes"] or 0
        if size > envelope["max_output_bytes_per_file"]:
            return (
                f"Generated file {item['filename']} is {size} bytes; the per-file ceiling is "
                f"{envelope['max_output_bytes_per_file']}."
            )
        total += size
    if total > envelope["max_total_output_bytes"]:
        return (
            f"The attempt produced {total} bytes of output; the total ceiling is "
            f"{envelope['max_total_output_bytes']}."
        )
    return None


def _record_digest(store, ident):
    if not ident:
        return None
    try:
        return store.get(ident)["digest"]
    except (KeyError, Invalid):
        return None


def _predecessor(store, attempt_id, previous):
    """Bind this attempt to the previous one's artifacts by digest.

    This mirrors `_revision_inputs` in `symplex/connectors/compute.py`: a revision is
    created by an explicit predecessor, and the predecessor is identified by content
    digest rather than by name, so a later attempt cannot silently claim an earlier
    attempt's outputs.
    """
    if previous is None:
        return None
    result = previous["result"]
    return {
        "attempt": previous["attempt"],
        "attempt_record_id": attempt_id,
        "attempt_record_digest": _record_digest(store, attempt_id),
        "package_id": result["package_id"],
        "package_digest": _record_digest(store, result["package_id"]),
        "run_id": result["run_id"],
        "run_digest": _record_digest(store, result["run_id"]),
        "file_ids": result["file_ids"][:MAX_REVISION_FILES],
        "files": [
            {
                "filename": f["filename"],
                "id": f["id"],
                "content_sha256": f["sha256"],
                "bytes": f["bytes"],
            }
            for f in result["files"][:MAX_RECORDED_FILES]
        ],
        "failure_kind": previous["failure_kind"],
        "authority": "Generated predecessor artifacts; execution does not establish scientific validity",
    }


def default_host_verification(request):
    """Host-owned recomputation. The agent supplies bytes; the host supplies the verdict.

    Prefers the full comparison path (`experiments.compare_computation`) when the run
    carries a frozen protocol, and otherwise recomputes the plan's protected numeric
    checks directly (`numerics.execute_numeric_checks`). Both are host code operating on
    generated CSV bytes; neither consults anything the agent reported about the outcome.

    A host failure to evaluate is reported as a failure, not as an absence: numerics
    fails closed on purpose, and an unevaluable output is not a passing one.
    """
    store, problem_id = request["store"], request["problem_id"]
    result, checks = request["result"], request["protected_checks"]
    if not result.get("package_id") and not (result.get("run_id") and result.get("file_ids")):
        return {
            "status": "unavailable",
            "all_passed": False,
            "reason": "The attempt recorded no collected run or generated file IDs for the host to read.",
        }
    if result.get("package_id"):
        from symplex.evaluation.experiments import compare_computation

        try:
            comparison_id = compare_computation(store, problem_id, result["package_id"])
        except (Invalid, ValueError, KeyError, OSError) as exc:
            comparison_id = None
            comparison_error = str(exc)[:1200]
        else:
            comparison = store.get(comparison_id)["data"]
            numerical = comparison.get("numerical_verification", {})
            return {
                "status": numerical.get("status", "unavailable"),
                "all_passed": bool(numerical.get("all_passed")),
                "method": "experiments.compare_computation",
                "comparison_id": comparison_id,
                "numerical_verification_id": comparison.get("numerical_verification_id"),
                "failed_check_ids": numerical.get("failed_check_ids", []),
                "check_count": numerical.get("check_count", 0),
                "pareto_alternative_ids": comparison.get("pareto_alternative_ids", []),
            }
        if not checks:
            return {
                "status": "failed",
                "all_passed": False,
                "method": "experiments.compare_computation",
                "reason": comparison_error,
            }
    if not checks:
        return {
            "status": "unavailable",
            "all_passed": False,
            "reason": "The plan declared no host-recomputable numeric check, so there is nothing for the host to verify.",
        }
    from symplex.evaluation.numerics import execute_numeric_checks

    try:
        numerical = execute_numeric_checks(
            store, problem_id, result["run_id"], result["file_ids"], checks
        )
    except (Invalid, ValueError, KeyError, OSError) as exc:
        return {
            "status": "failed",
            "all_passed": False,
            "method": "numerics.execute_numeric_checks",
            "reason": str(exc)[:1200],
            "failed_check_ids": [c["id"] for c in checks],
        }
    return {
        "status": numerical["status"],
        "all_passed": numerical["all_passed"],
        "method": "numerics.execute_numeric_checks",
        "failed_check_ids": [c["id"] for c in numerical["checks"] if not c["passed"]],
        "check_count": len(numerical["checks"]),
        "checks_digest": numerical.get("checks_digest"),
        "source_manifest": numerical.get("source_manifest", []),
    }


def _normalize_host(verification):
    if not isinstance(verification, dict):
        raise Invalid("Host verification must return a mapping")
    status = verification.get("status")
    if status not in ("checked", "failed", "unavailable"):
        raise Invalid("Host verification status must be checked, failed or unavailable")
    passed = bool(verification.get("all_passed")) and status == "checked"
    data = {
        key: value
        for key, value in verification.items()
        if key not in ("status", "all_passed", "authority")
    }
    return {
        **data,
        "status": status,
        "all_passed": passed,
        # Fixed by the host. An agent cannot relabel its own report as host-recomputed.
        "authority": HOST,
        "independently_validated": False,
        "scope": (
            "Host recomputation of generated bytes under frozen checks. It verifies the "
            "recorded numbers against declared limits; it does not validate the model."
        ),
    }


def _diagnostic_failure(diagnostics, declared_count):
    """Turn an unsatisfactory self-report into a typed failure the loop can act on."""
    failed = diagnostics["failed_ids"]
    unreported = diagnostics["unreported_ids"]
    undeclared = diagnostics["undeclared_ids"]
    if not failed and not unreported and not undeclared and diagnostics["reported_count"]:
        return None, None
    parts = []
    if failed:
        parts.append("failed: " + ", ".join(failed[:8]))
    if unreported:
        parts.append("declared but not reported: " + ", ".join(unreported[:8]))
    if undeclared:
        parts.append("reported but not declared: " + ", ".join(undeclared[:8]))
    if not diagnostics["reported_count"]:
        parts.append(f"no outcome reported for any of the {declared_count} declared tests")
    failure = ExecutionFailure(
        kind="assertion_failure",
        summary="The agent's own test report is not satisfied -- " + "; ".join(parts)[:900],
        failing_test_id=failed[0] if failed else None,
        signals=["maker test report"],
        evidence="; ".join(parts)[:1200],
    )
    note = (
        "Run and report an outcome for every declared test, exactly once each. An "
        "unreported test is not a passing test, and a reported test that was never "
        "declared is not part of the contract this plan was validated against."
    )
    return failure, note


def _attempt_record(**fields):
    return {
        "version": VERSION,
        "independently_validated": False,
        "authority_note": (
            "agent_diagnostics are maker_reported and are not evidence. host_verification "
            "is recomputed by the host from generated bytes. They are recorded separately "
            "and are never combined into a single verdict."
        ),
        "scope": SCOPE,
        **fields,
    }


def author_and_verify(
    store,
    problem_id,
    plan,
    *,
    execute,
    attempts=DEFAULT_ATTEMPTS,
    host_verify=None,
    budget=None,
    cancel=None,
    bundle=None,
    instruction="",
    require_protected_claim=True,
):
    """Author, execute, revise and verify one model, and record every attempt.

    `execute` is the injected sandbox call. It receives a request mapping carrying the
    attempt number, the validated plan, the guidance issued after the previous failure,
    the digest-bound predecessor, the bundle identity and the resource envelope, and it
    returns a mapping with `stdout`, `stderr`, `files`, `agent_tests`, and optionally the
    `package_id`, `run_id` and `file_ids` of what it collected. Injecting it keeps this
    loop testable offline: no provider, no network, no cost.

    `host_verify` defaults to `default_host_verification`, which calls the existing
    host-owned path. It can be injected for testing, but nothing an agent produces can
    reach it: the loop passes the host the store, the problem and the frozen checks, and
    takes the host's answer as given.

    Termination is always one of `converged`, `attempts_exhausted`, `escalated_to_plan`,
    `budget_exhausted` or `cancelled`. `converged` requires all three of: the program ran
    without a classified failure, the agent's own tests all reported pass, and the host's
    recomputation passed. Anything less returns partial results with an honest status.
    """
    if not callable(execute):
        raise Invalid("Inject a callable sandbox executor")
    if host_verify is not None and not callable(host_verify):
        raise Invalid("Host verification must be callable")
    if isinstance(attempts, bool) or not isinstance(attempts, int) or not 1 <= attempts <= MAX_ATTEMPTS:
        raise Invalid(f"Attempts must be an integer between 1 and {MAX_ATTEMPTS}")
    if not isinstance(instruction, str) or len(instruction) > 12000:
        raise Invalid("Instruction must be bounded text")

    problem = store.get(problem_id)
    if problem["kind"] != "workspace_problem" or problem["stale"]:
        raise Invalid("Select a current problem")

    # Cheap rejection first. An incoherent plan must never reach a paid execution.
    validation = validate_plan(plan, require_protected_claim=require_protected_claim)
    parsed = parse_plan(plan)
    protected = protected_subset(parsed.tests)
    verify = host_verify or default_host_verification
    envelope = _envelope(attempts)
    bundle_identity = (
        {
            "filename": bundle.get("filename"),
            "bundle_digest": bundle.get("bundle_digest"),
            "sha256": bundle.get("sha256"),
            "bytes": bundle.get("bytes"),
            "module_names": bundle.get("module_names", [])[:32],
            "status": bundle.get("status"),
            "optional": "The agent may import the bundle or implement its own routines.",
        }
        if isinstance(bundle, dict)
        else None
    )

    attempt_ids, summaries, discrepancies = [], [], []
    discrepancy_ids = []
    kind_counts = {}
    previous = None
    previous_attempt_id = None
    status = "attempts_exhausted"
    escalation = None
    final = None
    host_result = None
    guidance = None

    for index in range(1, attempts + 1):
        if cancel is not None and cancel.is_set():
            status = "cancelled"
            break
        reservation = None
        if budget is not None:
            try:
                reservation = budget.reserve(model_requests=1)
            except BudgetExhausted as exc:
                status = "budget_exhausted"
                escalation = {
                    "escalate": True,
                    "target": "metareasoner",
                    "reason": str(exc)[:800],
                }
                break

        request = {
            "attempt": index,
            "attempt_budget": attempts,
            "problem_id": problem_id,
            "problem_digest": problem["digest"],
            "instruction": instruction,
            "plan": validation["plan"],
            "plan_digest": validation["plan_digest"],
            "guidance": guidance,
            "predecessor": _predecessor(store, previous_attempt_id, previous),
            "bundle": bundle_identity,
            "protected_check_ids": protected["protected_ids"],
            "protected_checks": protected["numeric_checks"],
            "declared_tests": [t.model_dump() for t in parsed.tests],
            "resource_envelope": envelope,
        }
        try:
            raw = execute(request)
        finally:
            if reservation is not None:
                budget.settle(reservation, model_requests=1)

        result = _normalize_result(raw)
        breach = _envelope_breach(result, envelope)
        parsed_failure = parse_execution_failure(
            result["stdout"], result["stderr"], result["files"]
        )
        diagnostics = summarize_outcomes(parsed.tests, result["agent_tests"])
        diagnostic_note = None

        if breach is not None:
            failure = ExecutionFailure(
                kind="resource_exhausted",
                summary=breach,
                signals=["host resource envelope"],
                evidence=breach[:1200],
            )
        elif parsed_failure["failure"] is not None:
            failure = ExecutionFailure.model_validate(parsed_failure["failure"])
        else:
            failure, diagnostic_note = _diagnostic_failure(diagnostics, len(parsed.tests))

        attempt_status = "failed"
        host_result = None
        discrepancy = None
        if failure is None:
            # The agent's code ran and its own tests pass. That is where its authority
            # ends; from here the host recomputes and the agent cannot influence it.
            host_result = _normalize_host(
                verify(
                    {
                        "store": store,
                        "problem_id": problem_id,
                        "attempt": index,
                        "result": result,
                        "protected_checks": protected["numeric_checks"],
                        "protected_check_ids": protected["protected_ids"],
                        "plan_digest": validation["plan_digest"],
                    }
                )
            )
            if host_result["all_passed"]:
                attempt_status = "converged"
            elif host_result["status"] == "failed":
                attempt_status = "maker_host_discrepancy"
                failed_ids = list(host_result.get("failed_check_ids") or [])
                discrepancy = {
                    "label": "MAKER_HOST_DISCREPANCY",
                    "headline": DISCREPANCY_HEADLINE,
                    "attempt": index,
                    "agent_authority": MAKER,
                    "agent_reported_all_passed": True,
                    "agent_passed_test_ids": diagnostics["passed_ids"],
                    "host_authority": HOST,
                    "host_status": host_result["status"],
                    "host_all_passed": False,
                    "host_method": host_result.get("method"),
                    "host_reason": host_result.get("reason"),
                    "host_failed_check_ids": failed_ids[:32],
                    "contradicted_test_ids": [
                        i for i in protected["protected_ids"] if i in set(failed_ids)
                    ],
                    "unprotected_test_ids": [
                        e["id"] for e in protected["excluded"]
                    ][:32],
                    "audit_reference": "docs/release-audit.md finding 2: scientific acceptance still trusts maker-reported booleans.",
                    "implication": (
                        "The maker-reported outcome for this attempt is unsupported. Do not "
                        "report it as a result, and do not treat the passing tests as evidence "
                        "that the defect is elsewhere."
                    ),
                    "next_step": "Return to the modeling plan: the declared tests do not constrain what the host checks.",
                    "independently_validated": False,
                    "scope": SCOPE,
                }
            else:
                attempt_status = "unverified"
                failure = ExecutionFailure(
                    kind="contract_violation",
                    summary=(
                        "The program ran and its own tests passed, but the host had nothing to "
                        "recompute: "
                        + str(host_result.get("reason") or "no generated CSV was collected for the frozen checks.")
                    )[:900],
                    missing_outputs=protected["csv_filenames"][:16],
                    signals=["host verification unavailable"],
                    evidence=str(host_result.get("reason") or "")[:1200],
                )

        if failure is not None:
            kind_counts[failure.kind] = kind_counts.get(failure.kind, 0) + 1
            guidance = revision_guidance(failure)
            if diagnostic_note:
                guidance = {**guidance, "diagnostics_note": diagnostic_note}
            escalation = escalate(failure, repeats=kind_counts[failure.kind])
        else:
            guidance = None
            escalation = None

        record = _attempt_record(
            attempt=index,
            attempt_budget=attempts,
            status=attempt_status,
            plan_digest=validation["plan_digest"],
            bundle=bundle_identity,
            instruction=instruction[:2000],
            predecessor=request["predecessor"],
            guidance_issued=guidance,
            escalation=escalation,
            failure=failure.model_dump() if failure else None,
            failure_kind=failure.kind if failure else None,
            resource_envelope=envelope,
            resource_envelope_breach=breach,
            agent_diagnostics=diagnostics,
            host_verification=host_result,
            discrepancy=discrepancy,
            outputs=result["files"][:MAX_RECORDED_FILES],
            output_contract=parsed_failure["output_contract"],
            package_id=result["package_id"],
            run_id=result["run_id"],
            file_ids=result["file_ids"][:64],
            stdout_excerpt=result["stdout"][-MAX_STREAM_RECORD:],
            stderr_excerpt=result["stderr"][-MAX_STREAM_RECORD:],
            summary_excerpt=result["summary"],
        )
        attempt_id = store.put(ATTEMPT_KIND, record, problem_id)
        attempt_ids.append(attempt_id)
        summaries.append(
            {
                "attempt": index,
                "attempt_id": attempt_id,
                "status": attempt_status,
                "failure_kind": failure.kind if failure else None,
                "failure_summary": failure.summary[:400] if failure else None,
                "guidance_return_to": guidance["return_to"] if guidance else None,
                "agent_all_reported_passed": diagnostics["all_reported_passed"],
                "host_status": host_result["status"] if host_result else None,
                "host_all_passed": bool(host_result and host_result["all_passed"]),
                "output_filenames": [f["filename"] for f in result["files"]][:16],
            }
        )
        final = {
            "attempt": index,
            "attempt_id": attempt_id,
            "status": attempt_status,
            "package_id": result["package_id"],
            "run_id": result["run_id"],
            "file_ids": result["file_ids"][:64],
            "outputs": result["files"][:MAX_RECORDED_FILES],
        }
        previous = {
            "attempt": index,
            "result": result,
            "failure_kind": failure.kind if failure else None,
        }
        previous_attempt_id = attempt_id

        if discrepancy is not None:
            discrepancy = {**discrepancy, "attempt_id": attempt_id}
            discrepancy_ids.append(store.put(DISCREPANCY_KIND, discrepancy, problem_id))
            discrepancies.append(discrepancy)
            status = "escalated_to_plan"
            escalation = {
                "escalate": True,
                "target": "plan",
                "reason": DISCREPANCY_HEADLINE,
                "kind": "maker_host_discrepancy",
            }
            break
        if attempt_status == "converged":
            status = "converged"
            break
        # A structural failure, or one that has recurred past the point of usefulness,
        # leaves the code loop now rather than spending the remaining attempts on it.
        # An envelope escalation surfaces as budget_exhausted because the envelope, not
        # the model, is what ran out; `escalation` carries the precise reason either way.
        if escalation and escalation.get("escalate") and index < attempts:
            status = (
                "budget_exhausted"
                if escalation.get("target") == "metareasoner"
                else "escalated_to_plan"
            )
            break

    converged = status == "converged"
    headline = (
        DISCREPANCY_HEADLINE
        if discrepancies
        else "Converged: the program ran, the agent's own tests passed, and the host's independent recomputation passed. Scientific validity is still unestablished."
        if converged
        else "No converged model. "
        + {
            "attempts_exhausted": "The attempt budget was spent without a program that both runs and survives host recomputation.",
            "escalated_to_plan": "The loop stopped early and returned to the plan; further code attempts would not have addressed the failure.",
            "budget_exhausted": "The resource budget was exhausted before a converged attempt; these are partial results, not a result.",
            "cancelled": "The loop was cancelled; these are partial results.",
        }.get(status, "The loop terminated without convergence.")
    )

    return {
        "status": status,
        "converged": converged,
        "overall_success": converged and not discrepancies,
        "headline": headline,
        "attempts_used": len(attempt_ids),
        "attempt_budget": attempts,
        "attempt_ids": attempt_ids,
        "attempts": summaries,
        "final_attempt": final,
        "agent_diagnostics": {
            "authority": MAKER,
            **(summaries[-1] if summaries else {}),
            "note": "Agent-written tests are diagnostics. They are never independent evidence.",
        }
        if summaries
        else None,
        "host_verification": host_result,
        "discrepancies": discrepancies,
        "discrepancy_ids": discrepancy_ids,
        "has_discrepancy": bool(discrepancies),
        "escalation": escalation,
        "termination_reason": (
            escalation.get("reason")[:800]
            if escalation and escalation.get("reason")
            else "The attempt budget was spent."
            if status == "attempts_exhausted"
            else "Terminated on " + status + "."
        ),
        "plan_validation": {
            key: validation[key]
            for key in (
                "status",
                "plan_digest",
                "mechanism_family",
                "protected_test_ids",
                "checks_performed",
                "structural_difference",
            )
        },
        "plan_digest": validation["plan_digest"],
        "protected_test_ids": protected["protected_ids"],
        "unprotected_test_ids": [e["id"] for e in protected["excluded"]][:32],
        "bundle": bundle_identity,
        "resource_envelope": envelope,
        "loop_digest": digest(
            {
                "version": VERSION,
                "plan_digest": validation["plan_digest"],
                "bundle_digest": (bundle_identity or {}).get("bundle_digest"),
                "attempts": [
                    {k: s[k] for k in ("attempt", "status", "failure_kind")}
                    for s in summaries
                ],
                "status": status,
            }
        ),
        "independently_validated": False,
        "scope": SCOPE,
    }
