"""S1 -- distrust on a network: contagion, homophily, or a shared shock.

Generator: many independent rating episodes on a small signed network. Every episode ends
up with negativity clustered on the graph, and each was produced by exactly one of three
mechanisms.

  contagion        ties form at random; a user's negativity rises after the users they are
                   tied to have rated negatively, with a lag.
  homophily        ties form preferentially between users of similar temperament; nobody
                   transmits anything. Clustering is a property of who connected to whom.
  exogenous_shock  ties form at random; one global event raises everyone's negativity at
                   the same moment, and bursty activity makes it look local.

These three are famously hard to separate, and they are hard here on purpose: a lagged
neighbour regression finds a positive coefficient under all three. The separating evidence
is tie-formation time, which the pack supplies and which a naive analysis never opens.

Synthetic. Separating the three demonstrates inference mechanics, not a finding about any
real reputation system.
"""

import numpy as np

from symplex.core.contracts import Invalid
from symplex.domains.cases import (
    ORACLE_CONFIDENCE,
    CaseEndpoint,
    CaseMetric,
    CaseSpec,
    NumericCheck,
    check_knobs,
    check_seed,
    envelope,
    multiclass_brier_losses,
    predictions_of,
    probability,
    require_keys,
    scored,
    sealed,
    story,
    stream,
    table,
    unwrap,
)

CASE_ID = "s1"
GENERATOR = "s1_contagion_homophily_shock_v1"
DEFAULT_SEED = 7
KNOBS = {"episodes": (9, 48, 30), "users": (20, 60, 44), "steps": (24, 72, 48)}
MECHANISMS = ("contagion", "homophily", "exogenous_shock")
PLATFORM_OFFSET_STEPS = 2
CONTAGION_STRENGTH = 1.9
CONTAGION_LAG = 3
HOMOPHILY_SPREAD = 1.55
SHOCK_STRENGTH = 2.6
MODERATION_THRESHOLD = -8

SPEC = CaseSpec(
    id=CASE_ID,
    manifest_case="S1",
    domain="social_simulation",
    title="Which network mechanisms predict newly expressed distrust?",
    decision=(
        "Whether to spend human review on the users a distrust cluster is spreading from, "
        "on the pairs that formed the cluster, or on nothing at all because a single "
        "external event drove the whole episode."
    ),
    beneficiary="A trust-and-safety lead allocating a fixed human review queue.",
    mechanism_question=(
        "Did distrust transmit along ties, arrive with the ties themselves, or land on "
        "everyone at once?"
    ),
    rivals=[
        "Negativity transmits along existing ties with a lag.",
        "Ties form between similar users, so clustering never required transmission.",
        "One external event raised everyone's negativity at the same moment.",
        "Stable rater harshness and recipient reputation explain the whole pattern.",
    ],
    endpoints=[
        CaseEndpoint(
            id="mechanism",
            name="Probability over the three generating mechanisms",
            unit="probability simplex",
            meaning="Decides which intervention is even coherent for this episode.",
        )
    ],
    evidence_channels=[
        "Timestamped directed ratings with values, from two platforms.",
        "A tie table giving the step at which each pair first connected.",
        "A user table with join step and activity level, and no temperament field.",
    ],
    nuisance=[
        "Moderation deletes the most extreme negative ratings, which is MNAR missingness.",
        "One platform's timestamps run two steps ahead of the other's.",
        "Activity is bursty, so clustering in time is not evidence of clustering in cause.",
        "Ratings are expressed distrust, never verified fraud or private belief.",
    ],
    primary_metric=CaseMetric(
        id="mechanism_brier",
        name="Multiclass mechanism Brier score",
        lower_is_better=True,
        definition="Sum of squared errors across the three mechanism probabilities, averaged over episodes.",
    ),
    secondary_metrics=[
        CaseMetric(
            id="mechanism_accuracy",
            name="Top-choice accuracy",
            lower_is_better=False,
            definition="Fraction of episodes whose highest-probability mechanism is correct.",
        ),
        CaseMetric(
            id="hard_pair_brier",
            name="Contagion versus homophily Brier",
            lower_is_better=True,
            definition="Multiclass Brier restricted to episodes generated by the two confusable mechanisms.",
        ),
        CaseMetric(
            id="shock_recall",
            name="Shock recall",
            lower_is_better=False,
            definition="Fraction of shock episodes correctly identified as such.",
        ),
    ],
    baseline_name="Lagged neighbour regression with a synchrony test",
    baseline_rationale=(
        "The standard published analysis: measure whether a user's negativity follows their "
        "neighbours' negativity with a lag, and check whether onsets are globally "
        "synchronised. It identifies the shock episodes well and cannot separate the other "
        "two, which is exactly the known limitation of that design."
    ),
    oracle_rationale=(
        "The planted mechanism at declared confidence. It is a headroom marker, not a "
        "target: no estimator can reach it from these observations."
    ),
    trivial_name="Uniform over the three mechanisms",
    hidden_markers=[
        "mechanism_by_episode",
        "contagion_strength_by_episode",
        "shock_step_by_episode",
        "temperament_by_user",
        "tie_formation_rule_by_episode",
        "platform_clock_offset_steps",
    ],
    tables=["s1_ratings.csv", "s1_ties.csv", "s1_users.csv"],
    knobs=["episodes", "users", "steps"],
    limits=(
        "Ratings measure expressed distrust, not fraud or belief. Separating three "
        "simulators is not evidence about influence in a real reputation system."
    ),
)

NUMERIC_CHECKS = [
    NumericCheck(
        id="s1_rating_scale",
        operation="bounds",
        csv_filename="s1_ratings.csv",
        columns=["rating"],
        group_columns=["episode_id"],
        time_column=None,
        row_filters=[{"column": "retained", "equals": "yes"}],
        lower=-10.0,
        upper=10.0,
        reference_value=None,
        tolerance=0.0,
        direction=None,
        units="platform rating points",
        rationale="The rating scale is declared; a value outside it would break the sign convention.",
    ),
    NumericCheck(
        id="s1_tie_steps_finite",
        operation="finite",
        csv_filename="s1_ties.csv",
        columns=["first_link_step"],
        group_columns=["episode_id"],
        time_column=None,
        row_filters=[],
        lower=None,
        upper=None,
        reference_value=None,
        tolerance=0.0,
        direction=None,
        units="steps from episode start",
        rationale="Tie-formation time is the evidence that separates homophily from contagion.",
    ),
]


def _sigmoid(x):
    return 1.0 / (1.0 + np.exp(-np.clip(x, -30, 30)))


def _episode(rng, users, steps, mechanism):
    temperament = rng.normal(0, 1.0, size=users)
    activity = np.clip(rng.gamma(2.4, 0.10, size=users), 0.03, 0.55)
    pairs = []
    target_ties = int(users * 3.0)
    if mechanism == "homophily":
        candidates = [(i, j) for i in range(users) for j in range(i + 1, users)]
        weights = np.array(
            [np.exp(-HOMOPHILY_SPREAD * abs(temperament[i] - temperament[j])) for i, j in candidates]
        )
        weights = weights / weights.sum()
        chosen = rng.choice(len(candidates), size=min(target_ties, len(candidates)), replace=False, p=weights)
        for index in chosen:
            i, j = candidates[index]
            similarity = np.exp(-abs(temperament[i] - temperament[j]))
            step = int(np.clip(rng.integers(0, steps) * (1.0 - 0.35 * similarity), 0, steps - 1))
            pairs.append((i, j, step))
    else:
        seen = set()
        while len(pairs) < target_ties:
            i, j = sorted(rng.integers(0, users, size=2).tolist())
            if i == j or (i, j) in seen:
                continue
            seen.add((i, j))
            pairs.append((i, j, int(rng.integers(0, steps))))
    neighbours = {i: [] for i in range(users)}
    for i, j, step in pairs:
        neighbours[i].append((j, step))
        neighbours[j].append((i, step))
    shock_step = int(rng.integers(int(steps * 0.3), int(steps * 0.7)))
    strength = float(rng.uniform(0.7, 1.0)) * CONTAGION_STRENGTH
    if mechanism == "homophily":
        base = -0.9 + 1.5 * temperament
    elif mechanism == "contagion":
        base = -0.9 + 0.55 * temperament
    else:
        base = -1.75 + 0.55 * temperament
    negative_history = np.zeros((users, steps), dtype=float)
    ratings = []
    for t in range(steps):
        boost = np.zeros(users)
        if mechanism == "contagion" and t >= CONTAGION_LAG:
            window = negative_history[:, max(0, t - CONTAGION_LAG) : t]
            for i in range(users):
                linked = [j for j, step in neighbours[i] if step <= t - 1]
                if linked:
                    boost[i] = strength * float(window[linked].sum()) / (len(linked) + 1.0)
        elif mechanism == "exogenous_shock" and t >= shock_step:
            boost[:] = SHOCK_STRENGTH * np.exp(-(t - shock_step) / 11.0)
        propensity = _sigmoid(base + boost)
        acting = rng.random(users) < activity
        for i in np.flatnonzero(acting):
            linked = [j for j, step in neighbours[i] if step <= t]
            if not linked:
                continue
            target = int(linked[int(rng.integers(0, len(linked)))])
            negative = bool(rng.random() < propensity[i])
            value = int(-rng.integers(1, 11)) if negative else int(rng.integers(1, 11))
            ratings.append((t, int(i), target, value))
            if negative:
                negative_history[i, t] += 1.0
    return {
        "temperament": temperament,
        "activity": activity,
        "pairs": pairs,
        "ratings": ratings,
        "shock_step": shock_step if mechanism == "exogenous_shock" else None,
        "strength": strength if mechanism == "contagion" else None,
    }


def _simulate(seed, knobs):
    episodes, users, steps = knobs["episodes"], knobs["users"], knobs["steps"]
    picker = stream(seed, "s1/mechanism")
    out = []
    for e in range(episodes):
        mechanism = MECHANISMS[int(picker.integers(0, len(MECHANISMS)))]
        rng = stream(seed, f"s1/episode/{e}")
        record = _episode(rng, users, steps, mechanism)
        record["id"] = f"ep{e:02d}"
        record["mechanism"] = mechanism
        out.append(record)
    return out


def generate(seed=DEFAULT_SEED, **knobs):
    seed = check_seed(seed)
    resolved = check_knobs(knobs, KNOBS)
    episodes = _simulate(seed, resolved)
    moderation = stream(seed, "s1/moderation")
    rating_rows, tie_rows, user_rows = [], [], []
    for record in episodes:
        platform = {
            i: ("platform_b" if i % 2 else "platform_a") for i in range(resolved["users"])
        }
        for step, rater, ratee, value in record["ratings"]:
            deleted = value <= MODERATION_THRESHOLD and moderation.random() < 0.45
            offset = PLATFORM_OFFSET_STEPS if platform[rater] == "platform_b" else 0
            rating_rows.append(
                {
                    "episode_id": record["id"],
                    "step": step + offset,
                    "rater_id": f"u{rater:02d}",
                    "ratee_id": f"u{ratee:02d}",
                    "rating": None if deleted else value,
                    "platform": platform[rater],
                    "retained": "no" if deleted else "yes",
                }
            )
        for i, j, step in record["pairs"]:
            tie_rows.append(
                {
                    "episode_id": record["id"],
                    "user_a": f"u{i:02d}",
                    "user_b": f"u{j:02d}",
                    "first_link_step": step,
                }
            )
        for i in range(resolved["users"]):
            user_rows.append(
                {
                    "episode_id": record["id"],
                    "user_id": f"u{i:02d}",
                    "platform": platform[i],
                    "activity_rate": round(float(record["activity"][i]), 4),
                }
            )
    tables = {
        "s1_ratings.csv": table(
            ["episode_id", "step", "rater_id", "ratee_id", "rating", "platform", "retained"],
            rating_rows,
        ),
        "s1_ties.csv": table(["episode_id", "user_a", "user_b", "first_link_step"], tie_rows),
        "s1_users.csv": table(["episode_id", "user_id", "platform", "activity_rate"], user_rows),
    }
    return envelope(
        SPEC,
        seed,
        resolved,
        GENERATOR,
        tables,
        question=(
            "For every episode, give a probability for each of the three mechanisms: "
            "negativity transmitted along ties, ties formed between similar users, or a "
            "single external event hit everyone at once. The three must sum to one."
        ),
        submission={
            "keys": "one entry per episode_id",
            "fields": {name: "probability in [0, 1]" for name in MECHANISMS},
            "constraint": "the three probabilities must sum to one within 0.001",
            "example_key": "ep00",
        },
        metadata={
            "mechanisms": list(MECHANISMS),
            "clock": (
                "Steps are reported on each platform's own clock. The two platforms were "
                "not synchronised and the pack does not state the offset."
            ),
            "missingness": (
                "Moderation removes some of the most extreme negative ratings; the row "
                "remains with an empty value so the deletion itself stays visible."
            ),
            "not_observed": [
                "any user temperament, trait or private belief",
                "which mechanism generated an episode",
                "the content of a rating or the transaction behind it",
            ],
        },
        limitations=[
            "Deleted ratings are exactly the strongest signal, and they are removed non-randomly.",
            "Episodes are short, so a lagged coefficient is estimated from few events.",
            "Expressed distrust is not fraud, harm or belief.",
        ],
    )


def truth(seed=DEFAULT_SEED, **knobs):
    seed = check_seed(seed)
    resolved = check_knobs(knobs, KNOBS)
    episodes = _simulate(seed, resolved)
    return sealed(
        SPEC,
        seed,
        resolved,
        GENERATOR,
        facts={
            "mechanism_by_episode": {r["id"]: r["mechanism"] for r in episodes},
            "contagion_strength_by_episode": {
                r["id"]: (round(r["strength"], 6) if r["strength"] is not None else None)
                for r in episodes
            },
            "shock_step_by_episode": {r["id"]: r["shock_step"] for r in episodes},
            "temperament_by_user": {
                r["id"]: [round(float(x), 4) for x in r["temperament"]] for r in episodes
            },
            "tie_formation_rule_by_episode": {
                r["id"]: ("similarity_weighted" if r["mechanism"] == "homophily" else "uniform_random")
                for r in episodes
            },
            "platform_clock_offset_steps": {
                "platform_a": 0,
                "platform_b": PLATFORM_OFFSET_STEPS,
            },
        },
        assumptions=[
            "One mechanism per episode, drawn uniformly and independently.",
            "Negativity is a Bernoulli draw from a logistic propensity each active step.",
            "Only the contagion world lets one user's negativity enter another's propensity.",
        ],
        support=(
            f"{resolved['episodes']} independent episodes of {resolved['users']} users over "
            f"{resolved['steps']} steps."
        ),
    )


def _features(payload):
    """A step-change statistic and a lagged neighbour statistic, from visible tables only."""
    by_episode = {}
    for row in payload["tables"]["s1_ratings.csv"]["rows"]:
        if row["retained"] != "yes" or row["rating"] is None:
            continue
        by_episode.setdefault(row["episode_id"], []).append(row)
    ties = {}
    for row in payload["tables"]["s1_ties.csv"]["rows"]:
        ties.setdefault(row["episode_id"], []).append(row)
    features = {}
    for episode, rows in by_episode.items():
        span = max(r["step"] for r in rows) + 1
        counts = np.zeros(span)
        negatives_per_step = np.zeros(span)
        for row in rows:
            counts[row["step"]] += 1.0
            if row["rating"] < 0:
                negatives_per_step[row["step"]] += 1.0
        window = 5
        jump = 0.0
        for t in range(window + 1, span - window):
            before = counts[t - window - 1 : t].sum()
            after = counts[t : t + window].sum()
            if before < 6 or after < 6:
                continue
            rise = negatives_per_step[t : t + window].sum() / after
            rise -= negatives_per_step[t - window - 1 : t].sum() / before
            jump = max(jump, float(rise))
        onset = {}
        for row in rows:
            if row["rating"] < 0:
                onset[row["rater_id"]] = min(onset.get(row["rater_id"], 10**6), row["step"])
        neighbours = {}
        for tie in ties.get(episode, []):
            neighbours.setdefault(tie["user_a"], []).append(tie["user_b"])
            neighbours.setdefault(tie["user_b"], []).append(tie["user_a"])
        follow, total = 0, 0
        for user, first in onset.items():
            earlier = [onset[n] for n in neighbours.get(user, []) if n in onset]
            if not earlier:
                continue
            total += 1
            follow += int(first > min(earlier))
        features[episode] = {
            "jump": jump,
            "lag": follow / total if total else 0.5,
        }
    return features


def baseline(seed=DEFAULT_SEED, **knobs):
    seed = check_seed(seed)
    resolved = check_knobs(knobs, KNOBS)
    payload = generate(seed, **resolved)
    features = _features(payload)
    values = {}
    for episode, feature in features.items():
        shock = float(np.clip(_sigmoid((feature["jump"] - 0.285) * 21.0), 0.05, 0.85))
        rest = 1.0 - shock
        contagion_share = float(np.clip(_sigmoid((feature["lag"] - 0.815) * 9.0), 0.35, 0.65))
        values[episode] = {
            "contagion": round(rest * contagion_share, 6),
            "homophily": round(rest * (1.0 - contagion_share), 6),
            "exogenous_shock": round(shock, 6),
        }
        total = sum(values[episode].values())
        values[episode] = {k: round(v / total, 6) for k, v in values[episode].items()}
    return predictions_of(
        "baseline", SPEC, values, "lagged_neighbour_with_synchrony_test", SPEC.baseline_rationale
    )


def oracle(seed=DEFAULT_SEED, **knobs):
    seed = check_seed(seed)
    resolved = check_knobs(knobs, KNOBS)
    facts = truth(seed, **resolved)["facts"]["mechanism_by_episode"]
    other = (1.0 - ORACLE_CONFIDENCE) / (len(MECHANISMS) - 1)
    values = {
        episode: {
            name: (ORACLE_CONFIDENCE if name == label else other) for name in MECHANISMS
        }
        for episode, label in facts.items()
    }
    return predictions_of("oracle", SPEC, values, "planted_mechanism_upper_bound", SPEC.oracle_rationale)


def trivial(seed=DEFAULT_SEED, **knobs):
    seed = check_seed(seed)
    resolved = check_knobs(knobs, KNOBS)
    facts = truth(seed, **resolved)["facts"]["mechanism_by_episode"]
    share = 1.0 / len(MECHANISMS)
    values = {episode: {name: share for name in MECHANISMS} for episode in facts}
    return predictions_of(
        "trivial", SPEC, values, "uniform_over_mechanisms", "Equal probability on all three mechanisms."
    )


def evaluate(predictions, seed=DEFAULT_SEED, **knobs):
    seed = check_seed(seed)
    resolved = check_knobs(knobs, KNOBS)
    actual = truth(seed, **resolved)["facts"]["mechanism_by_episode"]
    values = require_keys(unwrap(predictions), actual)
    for row in values.values():
        if not isinstance(row, dict) or set(row) != set(MECHANISMS):
            raise Invalid("Each S1 entry needs one probability per declared mechanism")
        for name in MECHANISMS:
            probability(row[name], "mechanism probability")
    losses = multiclass_brier_losses(values, actual, MECHANISMS)
    ordered = sorted(actual)
    top = [max(MECHANISMS, key=lambda name: values[k][name]) for k in ordered]
    correct = [top[i] == actual[k] for i, k in enumerate(ordered)]
    hard = [i for i, k in enumerate(ordered) if actual[k] in ("contagion", "homophily")]
    shocks = [i for i, k in enumerate(ordered) if actual[k] == "exogenous_shock"]
    return scored(
        SPEC,
        seed,
        primary=float(np.mean(losses)),
        secondary={
            "mechanism_accuracy": float(np.mean(correct)),
            "hard_pair_brier": float(np.mean([losses[i] for i in hard])) if hard else None,
            "shock_recall": float(np.mean([correct[i] for i in shocks])) if shocks else None,
            "episode_counts": {
                name: sum(1 for v in actual.values() if v == name) for name in MECHANISMS
            },
        },
        losses=losses,
        units=len(actual),
        notes=[
            "Episodes are independent; users inside an episode are not.",
            "A uniform prediction scores two thirds on this metric; that is the floor to beat.",
        ],
    )


def narrative():
    return story(
        SPEC,
        decision=(
            "A distrust cluster appeared on the graph this week. Review the users it seems "
            "to spread from, review the pairs that formed it, or review nothing because an "
            "external event drove all of it?"
        ),
        agent_task=(
            "Tell three mechanisms apart that all produce clustered negativity and all "
            "produce a positive lagged neighbour coefficient. The evidence that separates "
            "them is when ties formed relative to when negativity started: under homophily "
            "temperament predates the tie, under contagion the tie predates the negativity, "
            "and under a shock neither matters because onsets are synchronised."
        ),
        good_answer=(
            "A multiclass Brier well below the lagged-regression baseline, with the gain "
            "concentrated on the contagion-versus-homophily pair rather than on the easy "
            "shock episodes, and an explicit statement that a positive lag coefficient is "
            "consistent with all three."
        ),
        trap=(
            "The published design -- regress a user's negativity on their neighbours' lagged "
            "negativity -- returns a confident positive coefficient on homophily episodes "
            "where nothing was ever transmitted. This is the case's whole point."
        ),
        two_minutes=[
            "Show three episodes; the negativity clusters look the same in all three.",
            "Run the lagged neighbour regression; positive and significant in all three.",
            "Open s1_ties.csv and sort by first_link_step; the story changes.",
            "Run the baseline: it finds the shocks and coin-flips the other two.",
            "Reveal the planted mechanisms and the headroom to the oracle bound.",
            "Say the sentence: synthetic ratings, recovered mechanism, no real platform.",
        ],
    )
