function architectureView() {
  const nodes = [
    { id: "problem", n: "01", name: "Define the decision", role: "Problem DNA", kind: "problem_dna", text: "Goals, endpoints, system boundary, subquestions and assumptions.", module: "agents/solver.py" },
    { id: "complexity", n: "02", name: "Represent the system", role: "Semantic + computational", kind: "complex_system", text: "Entities, observations, units, clocks, mechanisms, rivals and interactions.", module: "modeling/complex_system.py" },
    { id: "evidence", n: "03", name: "Assemble the evidence", role: "Source synthesis", kind: "evidence_synthesis", text: "Sources, datasets and user context; contradictions and measurement gaps stay visible.", module: "evidence/synthesis.py" },
    { id: "lab", n: "04", name: "Make it executable", role: "Astra + hosted Python", kind: "compute_package", text: "Frozen experiments, baseline and rival models, reusable code and computed outputs.", module: "connectors/compute.py" },
    { id: "evolution", n: "05", name: "Test and compare", role: "Host checks + model critique", kind: "experiment_comparison", text: "CSV diagnostics, comparison contracts and failures feed the next investigation.", module: "evaluation/experiments.py" },
    { id: "deliverables", n: "06", name: "Make the result useful", role: "Decision brief + visuals", kind: "decision_brief", text: "Estimates, tradeoffs, recorded trajectories, uncertainty and next validation.", module: "agents/outcomes.py" },
  ];
  const archive = latest("search_archive");
  const assessments = related("execution_assessment");
  return head("SYMPLEX / SYSTEM MAP", "How the investigation runs.", "Follow the links from problem framing to evidence, system models, execution and evaluation. Recorded results inform the next action.") +
    `<section class="engine-controller"><div><span class="eyebrow">ACTION SELECTION</span><h2>Choose the next investigation step.</h2><p>Generate alternatives → select a test → observe the result → retain, revise or stop.</p></div><div class="engine-controller-detail"><strong>Persistent investigation state</strong><p>Rivals and parent versions · uncertainty · critiques · resource limits · user steering</p>${btn("Inspect agent workflow", "nav", "workflow", "quiet")}</div></section>` +
    `<div class="engine-map" aria-label="Six connected responsibilities; adaptive, not a mandatory linear pipeline">${nodes.map(node => `<button class="engine-node" data-action="nav" data-id="${node.id}"><span class="engine-node-top"><span>${node.n} / ${node.role}</span><span>${related(node.kind).length} recorded</span></span><h3>${node.name}</h3><p>${node.text}</p><small>${node.module} ↗</small></button>`).join("")}</div>` +
    `<p class="engine-feedback">↶ Test failures, conflicting evidence and user direction can trigger a new question, model revision or experiment.</p>` +
    `<section class="engine-foundation"><div><span class="eyebrow">EXECUTION FOUNDATION</span><h3>Contracts bind execution to its inputs.</h3><p>Scoped tools and budgets · frozen prompt versions · persisted outputs and usage · hash-linked files · explicit failure feedback</p></div><div>${btn("Inspect contracts", "nav", "harness")}${btn("Data & tool connectors", "nav", "connectors")}</div></section>` +
    `<div class="section-heading"><h3>What improvement means here</h3><span>Three separate scopes</span></div><div class="engine-scopes"><article><h3>The system model</h3><p>Revise mechanisms, observations or representations. Preserve competing explanations and test their consequences.</p><strong>Typed revisions + executed comparisons</strong></article><article><h3>The candidate solution</h3><p>Compare an explicit design or intervention under fixed assumptions. Retain useful tradeoffs and reversal conditions.</p><strong>Conditional exploration; external validity required</strong></article><article><h3>The investigation method</h3><p>Propose changes to search or instructions from measured failures. Promotion needs fresh-task comparisons at matched cost.</p><strong class="muted">Method proposals remain uninstalled</strong></article></div>` +
    `<details class="engine-boundary"><summary>Search design and current evidence</summary><p>The MAP-Elites-inspired archive groups executed candidates by representation family, evidence basis and frozen protocol. The fraction of frozen host numerical checks passed ranks candidates only within the same protocol. Parent selection also accounts for prior visits; this score does not measure scientific accuracy.</p>${archive ? artifact(archive, "Inspect this problem’s search archive") : '<p class="tiny">This problem has no recorded search-archive snapshot yet.</p>'}<p>${assessments.length} post-execution assessments recorded for this problem.</p><p>Specialist molecular, geographic, financial and population engines require an available runtime and domain-specific validation. The 3D viewer renders recorded state coordinates from those models.</p><p>${urlLink("https://arxiv.org/abs/1504.04909", "MAP-Elites paper ↗")} · ${urlLink("https://deepmind.google/blog/alphaevolve-a-gemini-powered-coding-agent-for-designing-advanced-algorithms/", "AlphaEvolve ↗")}</p></details>`;
}
